dist: bionic
os: linux
services:
  - docker
language: go
go:
  - "1.14.x"

cache:
  directories:
    - $GOPATH/pkg/mod

install:
  - bash scripts/start-nexus.sh

script:
  - make test
  - make vet
  - SKIP_S3_TESTS=1 NEXUS_URL=http://127.0.0.1:8081 NEXUS_USERNAME=admin NEXUS_PASSWORD=admin123 make testacc
#  - make website-test

branches:
  only:
    - master
    - develop

jobs:
  fast_finish: true
  allow_failures:
    - go: tip
